//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.Glance.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALS.Glance.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Flexor carpi radialis&lt;/h4&gt;&lt;p&gt;Flexor carpi radialis is a muscle of the human forearm that acts to flex and (radial) abduct the hand.&lt;/p&gt;&lt;p&gt;&lt;a class=&quot;btn btn-default&quot; href=&quot;http://en.wikipedia.org/wiki/Flexor_carpi_radialis_muscle&quot;&gt;Learn more &amp;raquo;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string HomeFlexorCarpiRadialis {
            get {
                return ResourceManager.GetString("HomeFlexorCarpiRadialis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;br /&gt;The electromyography (EMG) is a medical technique for evaluating and recording the electrical activity produced by skeletal muscles. The electrical potential generated by muscle cells is detected using an electromyograph, when these cells are electrically or neurologically activated. The EMG results can reveal nerve dysfunction, muscle dysfunction or problems with nerve-to-muscle signal transmission.&lt;/p&gt;&lt;p&gt;In human kinesiological electromyography, electrical signals from surface electrodes or wire  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeIntroduction {
            get {
                return ResourceManager.GetString("HomeIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sternocleidomastoid&lt;/h4&gt;&lt;p&gt;The sternocleidomastoid muscle, also known as sternomastoid and commonly abbreviated as SCM, is one of the largest and most superficial cervical muscles.&lt;/p&gt;&lt;p&gt;&lt;a class=&quot;btn btn-default&quot; href=&quot;http://en.wikipedia.org/wiki/Sternocleidomastoid_muscle&quot;&gt;Learn more &amp;raquo;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string HomeSternocleidomastoid {
            get {
                return ResourceManager.GetString("HomeSternocleidomastoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Tibialis anterior&lt;/h4&gt;&lt;p&gt;The tibialis anterior is a muscle that originates in the upper two-thirds of the lateral (outside) surface of the tibia and inserts into the medial cuneiform and first metatarsal bones of the foot.&lt;/p&gt;&lt;p&gt;&lt;a class=&quot;btn btn-default&quot; href=&quot;http://en.wikipedia.org/wiki/Tibialis_anterior_muscle&quot;&gt;Learn more &amp;raquo;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string HomeTibialisAnterior {
            get {
                return ResourceManager.GetString("HomeTibialisAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthnameEn.
        /// </summary>
        public static string MonthNameKey {
            get {
                return ResourceManager.GetString("MonthNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All records selected. Please click on the graph to apply filters..
        /// </summary>
        public static string PatientAllSelected {
            get {
                return ResourceManager.GetString("PatientAllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Top.
        /// </summary>
        public static string PatientBackToTop {
            get {
                return ResourceManager.GetString("PatientBackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Schemes.
        /// </summary>
        public static string PatientColorSchemes {
            get {
                return ResourceManager.GetString("PatientColorSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string PatientDetails {
            get {
                return ResourceManager.GetString("PatientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last EMG in range.
        /// </summary>
        public static string PatientEMG {
            get {
                return ResourceManager.GetString("PatientEMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope window size:.
        /// </summary>
        public static string PatientEnvelopeWindowSize {
            get {
                return ResourceManager.GetString("PatientEnvelopeWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string PatientHour {
            get {
                return ResourceManager.GetString("PatientHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string PatientLoading {
            get {
                return ResourceManager.GetString("PatientLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Measurements.
        /// </summary>
        public static string PatientMeasurements {
            get {
                return ResourceManager.GetString("PatientMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle.
        /// </summary>
        public static string PatientMuscle {
            get {
                return ResourceManager.GetString("PatientMuscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle failure threshold.
        /// </summary>
        public static string PatientMuscleFailure {
            get {
                return ResourceManager.GetString("PatientMuscleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        public static string PatientPrediction {
            get {
                return ResourceManager.GetString("PatientPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string PatientQuarter {
            get {
                return ResourceManager.GetString("PatientQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string PatientQuarterPrefix {
            get {
                return ResourceManager.GetString("PatientQuarterPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data used for prediction:.
        /// </summary>
        public static string PatientRegressionData {
            get {
                return ResourceManager.GetString("PatientRegressionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PatientRegressionDataAll {
            get {
                return ResourceManager.GetString("PatientRegressionDataAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 months.
        /// </summary>
        public static string PatientRegressionDataLast6Months {
            get {
                return ResourceManager.GetString("PatientRegressionDataLast6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        public static string PatientRegressionDataLastYear {
            get {
                return ResourceManager.GetString("PatientRegressionDataLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string PatientReset {
            get {
                return ResourceManager.GetString("PatientReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string PatientResume {
            get {
                return ResourceManager.GetString("PatientResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes were successfully saved..
        /// </summary>
        public static string PatientSaveMessage {
            get {
                return ResourceManager.GetString("PatientSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born On.
        /// </summary>
        public static string PatientsBornOn {
            get {
                return ResourceManager.GetString("PatientsBornOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosed On.
        /// </summary>
        public static string PatientsDiagnosedOn {
            get {
                return ResourceManager.GetString("PatientsDiagnosedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show failure threshold.
        /// </summary>
        public static string PatientShowFailureThresHold {
            get {
                return ResourceManager.GetString("PatientShowFailureThresHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;%filter-count&lt;/strong&gt; selected out of &lt;strong&gt;%total-count&lt;/strong&gt; records..
        /// </summary>
        public static string PatientSomeSelected {
            get {
                return ResourceManager.GetString("PatientSomeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Id.
        /// </summary>
        public static string PatientsPatientId {
            get {
                return ResourceManager.GetString("PatientsPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string PatientsSex {
            get {
                return ResourceManager.GetString("PatientsSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the bubbles to filter patients by gender..
        /// </summary>
        public static string PatientsTip1 {
            get {
                return ResourceManager.GetString("PatientsTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here to filter patients by name..
        /// </summary>
        public static string PatientsTip2 {
            get {
                return ResourceManager.GetString("PatientsTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view the patient summary..
        /// </summary>
        public static string PatientsTip3 {
            get {
                return ResourceManager.GetString("PatientsTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Age.
        /// </summary>
        public static string PatientsXAxisLabel {
            get {
                return ResourceManager.GetString("PatientsXAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Patients.
        /// </summary>
        public static string PatientsYAxisLabel {
            get {
                return ResourceManager.GetString("PatientsYAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string PatientTime {
            get {
                return ResourceManager.GetString("PatientTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Of Day.
        /// </summary>
        public static string PatientTimeOfDay {
            get {
                return ResourceManager.GetString("PatientTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodEn.
        /// </summary>
        public static string PatientTimeOfDayKey {
            get {
                return ResourceManager.GetString("PatientTimeOfDayKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on this donut chart to filter by quarter..
        /// </summary>
        public static string PatientTip1 {
            get {
                return ResourceManager.GetString("PatientTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to expand the panel..
        /// </summary>
        public static string PatientTip10 {
            get {
                return ResourceManager.GetString("PatientTip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to close the panel..
        /// </summary>
        public static string PatientTip11 {
            get {
                return ResourceManager.GetString("PatientTip11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on this row chart to filter by time of day..
        /// </summary>
        public static string PatientTip2 {
            get {
                return ResourceManager.GetString("PatientTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop to zoom in..
        /// </summary>
        public static string PatientTip3 {
            get {
                return ResourceManager.GetString("PatientTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to configure the prediction of results..
        /// </summary>
        public static string PatientTip4 {
            get {
                return ResourceManager.GetString("PatientTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop or use mouse wheel to zoom in..
        /// </summary>
        public static string PatientTip5 {
            get {
                return ResourceManager.GetString("PatientTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to toggle between normal and envelope view..
        /// </summary>
        public static string PatientTip7 {
            get {
                return ResourceManager.GetString("PatientTip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to reset the filters applied to the chart..
        /// </summary>
        public static string PatientTip8 {
            get {
                return ResourceManager.GetString("PatientTip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to collapse the panel..
        /// </summary>
        public static string PatientTip9 {
            get {
                return ResourceManager.GetString("PatientTip9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regression to predict future results.
        /// </summary>
        public static string PatientUseRegression {
            get {
                return ResourceManager.GetString("PatientUseRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SharedClose {
            get {
                return ResourceManager.GetString("SharedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}.
        /// </summary>
        public static string SharedDataTables {
            get {
                return ResourceManager.GetString("SharedDataTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SharedDate {
            get {
                return ResourceManager.GetString("SharedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string SharedLogin {
            get {
                return ResourceManager.GetString("SharedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string SharedLogoff {
            get {
                return ResourceManager.GetString("SharedLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string SharedManage {
            get {
                return ResourceManager.GetString("SharedManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ &quot;January&quot;, &quot;February&quot;, &quot;March&quot;, &quot;April&quot;, &quot;May&quot;, &quot;June&quot;, &quot;July&quot;, &quot;August&quot;, &quot;September&quot;, &quot;October&quot;, &quot;November&quot;, &quot;December&quot; ].
        /// </summary>
        public static string SharedMonths {
            get {
                return ResourceManager.GetString("SharedMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SharedName {
            get {
                return ResourceManager.GetString("SharedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string SharedPatients {
            get {
                return ResourceManager.GetString("SharedPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SharedSave {
            get {
                return ResourceManager.GetString("SharedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ &quot;Sun&quot;, &quot;Mon&quot;, &quot;Tue&quot;, &quot;Wed&quot;, &quot;Thu&quot;, &quot;Fri&quot;, &quot;Sat&quot; ].
        /// </summary>
        public static string SharedShortDays {
            get {
                return ResourceManager.GetString("SharedShortDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot; ].
        /// </summary>
        public static string SharedShortMonths {
            get {
                return ResourceManager.GetString("SharedShortMonths", resourceCulture);
            }
        }
    }
}
